node{
	stage('git Checkout'){
	checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitlab', url: 'http://192.168.23.128:88/root/pipaspcore.git']]])
	}

	stage('Build'){

	try{
	 sh '''
		cd ./frontend/frontend
		docker rmi frontend:latest 
		'''
	}
	finally{
	 
	 sh '''
		cd ./frontend/frontend
		docker build -t frontend:latest .
		docker login 192.168.23.128
		docker tag frontend:latest 192.168.23.128/docker/frontend:v3
		docker push 192.168.23.128/docker/frontend:v3 
	 '''
	  }
	}
	stage('Deploy'){
		try{
		sh '''
		cd ./frontend/frontend/deploy 
		kubectl delete  -f deployment.yml
	 	 
		''' 
		}finally{
		sh '''
		cd ./frontend/frontend/deploy  
		ls
		kubectl apply  -f deployment.yml 
		''' 
		} 
	}
}