apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-db
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
        - name: myapp-database
          image: mcr.microsoft.com/mssql/server
          ports:
           - containerPort: 1433
          env:
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "SA_PASSWORD"
              value: "Hangye1993"
            - name: "MSSQL_PID"
              value: "Express"

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-db-service
spec:
  selector:
    app: myapp-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
  
---

apiVersion: apps/v1
kind: Deployment
metadata:  
  name: myapp-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
  minReadySeconds: 5
 
  template:
    metadata:
      labels:
        app: myapp
        zone: prod
        version: v1
    spec:
      containers:
        - name: myapp-frontend
          image: hangyejiadao/frontend:v1
          ports:
            - containerPort:  80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: DEVELOPMENT
            - name: SQLSERVER_CONNECTIONSTRING
              value: "Server=sqlserver:30002;Database=myapp;User=sa;Password=Hangye1993;MultipleActiveResultSets=true;"

---

apiVersion: v1
kind: Service
metadata:
 name: myapp-svc
spec:
 selector:
   app: myapp
 type: NodePort
 ports:
  - port: 80
    nodePort: 30001