apiVersion: apps/v1
kind: Deployment
metadata:  
  name: myapp-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
  minReadySeconds: 5
 
  template:
    metadata:
      labels:
        app: myapp
        zone: prod
        version: v1
    spec:
      containers:
        - name: myapp-frontend
          image: 192.168.23.128/docker/frontend:v3
          ports:
            - containerPort:  80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: DEVELOPMENT
            - name: SQLSERVER_CONNECTIONSTRING
              value: "Server=myapp-db-service;Database=myapp;User=sa;Password=Hangye1993;MultipleActiveResultSets=true;"

---

apiVersion: v1
kind: Service
metadata:
 name: myapp-svc
spec:
 selector:
   app: myapp
 type: NodePort
 ports:
  - port: 80
    nodePort: 30001